language: node_js
# blocklist
branches:
  except:
  - Dev
node_js:
  - "8.2.1"
script:
  - echo "Deploying!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
